[project]
name = "czds_api_client"
version = "0.1.0"
authors = [
  { name="Dongmei Cao", email="dongmei.cao@icann.org" },
  { name="Egon Kidmose", email="egk@es.aau.dk" },
  { name="Eric Case", email="sraveh@users.noreply.github.com" },
  { name="John Jensen", email="egk@es.aau.dk" },
  { name="Simon", email="sraveh@users.noreply.github.com" },
  { name="Coder4", email="liheyuan@users.noreply.github.com"},
]
readme = "README.md"
requires-python = ">=3.7"
description = "A client for the CZDS APLI API"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests == 2.25.1",
    "types-requests==2.28.11.5",
    "types-setuptools==65.6.0.1",
]

[project.urls]
"Homepage" = "https://github.com/icann/czds-api-client-python"
"Bug Tracker" = "https://github.com/icann/czds-api-client-python/issues"

[tool.black]
line-length = 100
target-version = ['py37', 'py38', 'py39', 'py310']
extend-exclude = '''
(
  .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
include = '''
(
    ^/tests/
  | ^/src/
  | ^/setup[.]py
  | ^/conftest[.]py
)
'''

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["src", "tests"]
extend_skip = [".md", ".json"]
