# pyproject.toml file for a project called czds-apli-client writtein in python
[project]
name = "czds-api-client"
version = "0.1.0"
authors = [
  { name="Dongmei Cao", email="dongmei.cao@icann.org" },
  { name="Egon Kidmose", email="egk@es.aau.dk" },
  { name="Eric Case", email="sraveh@users.noreply.github.com" },
  { name="John Jensen", email="egk@es.aau.dk" },
  { name="Simon", email="sraveh@users.noreply.github.com" },
  { name="Coder4", email="liheyuan@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.7"
description = "A client for the CZDS APLI API"
homepage = "https://github.com/icann/czds-api-client-python"
license = "MIT"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests == 2.25.1",
    "types-requests==2.28.11.5",
    "types-setuptools==65.6.0.1"  
]

[project.urls]
"Homepage" = "https://github.com/icann/czds-api-client-python"
"Bug Tracker" = "https://github.com/icann/czds-api-client-python/issues"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.isort]
profile = "black"
src_paths = [".", "tests"]